In [1]:
import sys
print(sys.executable)

/Users/iwonbin/workspace/Study/boot/SKN28-1st-4team/.venv/bin/python3

# Model Group Manual

이 notebook은 `cohort grouping`의 수동 분류 출발점을 만든다.

목표:
- `brand + model_name` 기준으로 모델 인벤토리를 검토한다.
- 사람이 입력할 `major_category`를 준비한다.
- category별 체급 산정을 위한 기초 함수와 템플릿을 만든다.
- 이름 normalization은 display 값과 별개로 `_key` 컬럼을 만들어 안정적으로 관리한다.

In [2]:
from pathlib import Path

import pandas as pd
from IPython.display import display

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

DATA_CANDIDATES = [
    Path('data/cohort_grouping_input.csv'),
    Path('raw/models_cohort/cohort_generation/data/cohort_grouping_input.csv'),
]

for candidate in DATA_CANDIDATES:
    if candidate.exists():
        DATA_PATH = candidate.resolve()
        break
else:
    raise FileNotFoundError('cohort_grouping_input.csv not found from the current notebook working directory.')

df_raw = pd.read_csv(DATA_PATH, dtype=str)
df = df_raw.apply(lambda col: col.map(lambda value: None if isinstance(value, str) and value.strip() == '' else value))

DATA_PATH, df.shape

(PosixPath('/Users/iwonbin/workspace/Study/boot/SKN28-1st-4team/data_collection/raw/models_cohort/cohort_generation/data/cohort_grouping_input.csv'),
 (7754, 9))

In [3]:
display(df[['brand', 'model_name', 'level_name', 'class_name', 'launch_price_krw', 'displacement_cc', 'body_length_mm', 'body_width_mm', 'body_height_mm']].head(20))
df.shape

,brand,model_name,level_name,class_name,launch_price_krw,displacement_cc,body_length_mm,body_width_mm,body_height_mm
0,chevrolet,뉴 볼트 EV,(전기),프리미어,41300000,0,4140,1765,1595
1,chevrolet,더 넥스트 스파크,1.0,LS,10360000,999,3595,1595,1475
2,chevrolet,더 넥스트 스파크,1.0,LS 베이직,9990000,999,3595,1595,1475
3,chevrolet,더 넥스트 스파크,1.0,LS 베이직,9990000,999,3595,1595,1475
4,chevrolet,더 넥스트 스파크,1.0,LT,11340000,999,3595,1595,1475
5,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,995,3595,1595,1475
6,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,999,3595,1595,1475
7,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,999,3595,1595,1475
8,chevrolet,더 넥스트 스파크,1.0,LTZ,11360000,995,3595,1595,1475
9,chevrolet,더 넥스트 스파크,1.0,LTZ,11340000,999,3595,1595,1475
10,chevrolet,더 넥스트 스파크,1.0,LTZ,11340000,999,3595,1595,1475
11,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,11360000,995,3595,1595,1475
12,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,12060000,999,3595,1595,1475
13,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,12010000,999,3595,1595,1475
14,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 퍼펙트 블랙,15090000,999,3595,1595,1475
15,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 퍼펙트 블랙,15090000,999,3595,1595,1475
16,chevrolet,더 넥스트 스파크,1.0,에코 LS,14320000,999,3595,1595,1475
17,chevrolet,더 넥스트 스파크,1.0,에코 LS,14270000,999,3595,1595,1475
18,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,12710000,999,3595,1595,1475
19,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,14300000,999,3595,1595,1475

(7754, 9)

## Missing Displacement or Body Size Rows

우선 `배기량`과 `차 사이즈` 관련 컬럼 중 하나라도 비어 있거나, 값이 `0`인 row를 따로 뽑는다.
현재 데이터에서는 실제 missing이 빈 문자열이 아니라 `0`으로 들어간 경우가 많아서, `0`도 missing으로 간주한다.

현재 기준 컬럼은 아래 네 개를 사용한다.

- `displacement_cc`
- `body_length_mm`
- `body_width_mm`
- `body_height_mm`

In [4]:
required_columns = [
    'displacement_cc',
    'body_length_mm',
    'body_width_mm',
    'body_height_mm',
]

numeric_required = df[required_columns].apply(pd.to_numeric, errors="coerce")
missing_mask = numeric_required.isna() | numeric_required.le(0)

def collect_missing_fields(row: pd.Series) -> str:
    missing_cols = [column for column in required_columns if pd.isna(row[column]) or float(row[column]) <= 0]
    return ", ".join(missing_cols)

missing_size_or_displacement_rows = df.loc[missing_mask.any(axis=1)].copy()
missing_size_or_displacement_rows["missing_fields"] = numeric_required.loc[missing_mask.any(axis=1)].apply(collect_missing_fields, axis=1)

missing_size_or_displacement_model_summary = (
    missing_size_or_displacement_rows
    .groupby(["brand", "model_name"], dropna=False)
    .agg(
        missing_row_count=("model_name", "size"),
        missing_field_examples=("missing_fields", lambda s: ", ".join(list(dict.fromkeys(str(v) for v in s.dropna()))[:10])),
    )
    .reset_index()
    .sort_values(["missing_row_count", "brand", "model_name"], ascending=[False, True, True])
)

df_filtered = df.loc[~missing_mask.any(axis=1)].copy()
df = df_filtered.copy()

print("original rows:", len(df_raw))
print("removed rows:", len(missing_size_or_displacement_rows))
print("filtered rows:", len(df_filtered))
print("affected models:", len(missing_size_or_displacement_model_summary))

display(missing_size_or_displacement_model_summary.head(50))

display(df.head(20))

df.shape

original rows: 7754
removed rows: 1845
filtered rows: 5909
affected models: 186

,brand,model_name,missing_row_count,missing_field_examples
150,kia,봉고3,227,"displacement_cc, body_length_mm, body_width_mm..."
80,hyundai,포터2,219,"displacement_cc, body_length_mm, body_width_mm..."
78,hyundai,파비스,74,"displacement_cc, body_length_mm, body_width_mm..."
138,kia,더 뉴 봉고3,63,"displacement_cc, body_length_mm, body_width_mm..."
77,hyundai,트라고 엑시언트,51,"displacement_cc, body_length_mm, body_width_mm..."
16,hyundai,e마이티,50,"displacement_cc, body_length_mm, body_width_mm..."
76,hyundai,트라고,46,"displacement_cc, body_length_mm, body_width_mm..."
21,hyundai,그랜드스타렉스,42,"displacement_cc, body_length_mm, body_width_mm..."
65,hyundai,엑시언트 프로,42,"displacement_cc, body_length_mm, body_width_mm..."
64,hyundai,엑시언트,38,"displacement_cc, body_length_mm, body_width_mm..."
66,hyundai,올 뉴 마이티,37,"displacement_cc, body_length_mm, body_width_mm..."
15,hyundai,e-카운티,35,"displacement_cc, body_length_mm, body_width_mm..."
124,kia,뉴 그랜버드,33,"displacement_cc, body_length_mm, body_width_mm..."
98,kgm,무쏘,30,"displacement_cc, body_length_mm, body_width_mm..."
29,hyundai,뉴 카운티,26,"displacement_cc, body_length_mm, body_width_mm..."
118,kia,EV9,24,displacement_cc
60,hyundai,아이오닉5,20,displacement_cc
68,hyundai,유니버스,19,"displacement_cc, body_length_mm, body_width_mm..."
62,hyundai,아이오닉9,18,"displacement_cc, body_length_mm, body_width_mm..."
91,kgm,더 뉴 토레스,18,"displacement_cc, body_length_mm, body_width_mm..."
38,hyundai,더 뉴 아이오닉 5,16,"displacement_cc, displacement_cc, body_length_..."
179,renault,더 뉴 QM6,16,"displacement_cc, body_length_mm, body_width_mm..."
28,hyundai,뉴 슈퍼에어로시티,15,"displacement_cc, body_length_mm, body_width_mm..."
117,kia,EV6,15,displacement_cc
53,hyundai,쏘나타 더 브릴리언트,14,"displacement_cc, body_length_mm, body_width_mm..."
83,kgm,뉴 로디우스,14,"displacement_cc, body_length_mm, body_width_mm..."
39,hyundai,더 뉴 아이오닉 6,13,"displacement_cc, displacement_cc, body_length_..."
119,kia,K5,13,"displacement_cc, body_length_mm, body_width_mm..."
170,renault,SM5 노바,13,"displacement_cc, body_length_mm, body_width_mm..."
130,kia,더 뉴 EV6,12,"displacement_cc, body_length_mm, body_width_mm..."
140,kia,더 뉴 스포티지,12,"displacement_cc, body_length_mm, body_width_mm..."
146,kia,디 올 뉴 스포티지,12,"displacement_cc, body_length_mm, body_width_mm..."
123,kia,PV5,11,"displacement_cc, displacement_cc, body_height_mm"
176,renault,뉴 SM5 (신형),11,"displacement_cc, body_length_mm, body_width_mm..."
14,hyundai,e-에어로타운,10,"displacement_cc, body_length_mm, body_width_mm..."
105,kgm,코란도 C,10,"displacement_cc, body_length_mm, body_width_mm..."
114,kia,EV3,10,displacement_cc
115,kia,EV4,10,"displacement_cc, displacement_cc, body_length_..."
116,kia,EV5,10,displacement_cc
139,kia,더 뉴 셀토스,10,"displacement_cc, body_length_mm, body_width_mm..."
183,renault,아르카나,10,"displacement_cc, body_length_mm, body_width_mm..."
50,hyundai,싼타페 더스타일,9,"displacement_cc, body_length_mm, body_width_mm..."
61,hyundai,아이오닉6,9,displacement_cc
79,hyundai,팰리세이드,9,"displacement_cc, body_length_mm, body_width_mm..."
100,kgm,무쏘 스포츠,9,"displacement_cc, body_length_mm, body_width_mm..."
24,hyundai,그린시티,8,"displacement_cc, body_length_mm, body_width_mm..."
36,hyundai,더 뉴 아반떼 N,8,"displacement_cc, body_length_mm, body_width_mm..."
51,hyundai,싼타페CM,8,"displacement_cc, body_length_mm, body_width_mm..."
82,kgm,G4 렉스턴,8,"displacement_cc, body_length_mm, body_width_mm..."
92,kgm,더 뉴 티볼리,8,"displacement_cc, body_length_mm, body_width_mm..."

,brand,model_name,level_name,class_name,launch_price_krw,displacement_cc,body_length_mm,body_width_mm,body_height_mm
1,chevrolet,더 넥스트 스파크,1.0,LS,10360000,999,3595,1595,1475
2,chevrolet,더 넥스트 스파크,1.0,LS 베이직,9990000,999,3595,1595,1475
3,chevrolet,더 넥스트 스파크,1.0,LS 베이직,9990000,999,3595,1595,1475
4,chevrolet,더 넥스트 스파크,1.0,LT,11340000,999,3595,1595,1475
5,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,995,3595,1595,1475
6,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,999,3595,1595,1475
7,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,999,3595,1595,1475
8,chevrolet,더 넥스트 스파크,1.0,LTZ,11360000,995,3595,1595,1475
9,chevrolet,더 넥스트 스파크,1.0,LTZ,11340000,999,3595,1595,1475
10,chevrolet,더 넥스트 스파크,1.0,LTZ,11340000,999,3595,1595,1475
11,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,11360000,995,3595,1595,1475
12,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,12060000,999,3595,1595,1475
13,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,12010000,999,3595,1595,1475
14,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 퍼펙트 블랙,15090000,999,3595,1595,1475
15,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 퍼펙트 블랙,15090000,999,3595,1595,1475
16,chevrolet,더 넥스트 스파크,1.0,에코 LS,14320000,999,3595,1595,1475
17,chevrolet,더 넥스트 스파크,1.0,에코 LS,14270000,999,3595,1595,1475
18,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,12710000,999,3595,1595,1475
19,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,14300000,999,3595,1595,1475
20,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,14300000,999,3595,1595,1475

(5909, 9)

## Model Category Mapping Goal

이 단계의 목표는 `brand + model_name` 단위 매핑 테이블을 만드는 것이다.
즉 trim이 달라도 같은 모델이면 같은 차체/카테고리로 묶는다는 가정을 쓴다.

agent output은 최대한 단순하게 유지한다.
- `brand`
- `model_name`
- `major_category`

In [5]:
import sys
from pathlib import Path

NOTEBOOK_DIR = Path.cwd().resolve()
if str(NOTEBOOK_DIR) not in sys.path:
    sys.path.append(str(NOTEBOOK_DIR))

from cohort_mapping import (
    CohortAgentConfig,
    VehicleCategoryMappingInput,
    VehicleCategoryMappingOutput,
    apply_mapping_table,
    build_mapping_requests,
    dataframe_to_mapping_inputs,
    get_input_schema,
    get_output_schema,
    get_pending_requests,
    load_mapping_table,
    mapping_outputs_to_frame,
    run_category_mapping_sync,
)
from cohort_mapping.config import is_agent_env_ready

## Input / Output Schema

schema는 단순하게 `brand + model_name`에 대한 category mapping만 다룬다.

In [6]:
input_schema_fields = pd.DataFrame(
    [
        {
            "field": name,
            "annotation": str(field.annotation),
            "required": field.is_required(),
        }
        for name, field in VehicleCategoryMappingInput.model_fields.items()
    ]
)

output_schema_fields = pd.DataFrame(
    [
        {
            "field": name,
            "annotation": str(field.annotation),
            "required": field.is_required(),
        }
        for name, field in VehicleCategoryMappingOutput.model_fields.items()
    ]
)

display(input_schema_fields)
display(output_schema_fields)

                 field     annotation  required
0                brand  <class 'str'>      True
1           model_name  <class 'str'>      True
2  class_name_examples      list[str]     False
3  level_name_examples      list[str]     False
4      context_summary     str | None     False

            field              annotation  required
0           brand           <class 'str'>      True
1      model_name           <class 'str'>      True
2  major_category  <enum 'MajorCategory'>      True
3     search_used          <class 'bool'>     False
4            note              str | None     False

## Build Mapping Requests

`brand + model_name` 기준으로 request table을 만든다.
`class_name`과 `level_name`은 examples로만 전달한다.

In [7]:
requests_df = build_mapping_requests(df)
requests_path = DATA_PATH.parent / "model_category_mapping_requests.csv"
requests_df.to_csv(requests_path, index=False)

print("brand+model unique rows:", len(requests_df))
print("model_name unique count:", requests_df["model_name"].nunique())

display(requests_df.head(30))
requests_path, requests_df.shape

brand+model unique rows: 267
model_name unique count: 267

,brand,model_name,class_name_examples,level_name_examples,context_summary
0,chevrolet,더 넥스트 스파크,"[LS, LS 베이직, LT, LT 플러스, LTZ, 스페셜 에디션 패션, 스페셜 ...",[1.0],"class_name_examples=LS, LS 베이직, LT, LT 플러스, LT..."
1,chevrolet,더 뉴 말리부,"[LS, LS 디럭스, LT, LT 디럭스, 레드라인 프리미어, 레드라인 프리미어 ...","[1.3 터보, 1.6 디젤, 1.8 HEV, 2.0 터보]","class_name_examples=LS, LS 디럭스, LT, LT 디럭스, 레드..."
2,chevrolet,더 뉴 스파크,"[LS, LS 베이직, LT, 레드픽 에디션, 마이핏 LT, 마이핏 에디션, 프리미어]",[1.0],"class_name_examples=LS, LS 베이직, LT, 레드픽 에디션, 마..."
3,chevrolet,더 뉴 아베오,"[L, LS, LT]","[1.4 터보, 1.4 터보 해치백]","class_name_examples=L, LS, LT | level_name_exa..."
4,chevrolet,더 뉴 카마로 SS,"[-, 볼케이노 레드]",[6.2 V8],"class_name_examples=-, 볼케이노 레드 | level_name_ex..."
5,chevrolet,더 뉴 트랙스,"[LS, LS 디럭스, LT, LT 디럭스, LT 코어, LTZ, 레드라인 LT 코...","[1.4 가솔린, 1.6 디젤]","class_name_examples=LS, LS 디럭스, LT, LT 디럭스, LT..."
6,chevrolet,더 뉴 트레일블레이저,"[LT, RS, 액티브, 프리미어]","[1.3 터보 2WD, 1.3 터보 AWD]","class_name_examples=LT, RS, 액티브, 프리미어 | level_..."
7,chevrolet,리얼 뉴 콜로라도,"[익스트림, Z71-X, Z71-X 미드나잇, 익스트림-X]","[3.6 V6, 3.6 V6 4WD]","class_name_examples=익스트림, Z71-X, Z71-X 미드나잇, 익..."
8,chevrolet,말리부,"[LS, LS 디럭스 팩, LT, LT 디럭스팩, LTZ, LTZ 디럭스팩(블랙휠)...","[2.0, 2.0 디젤, 2.4]","class_name_examples=LS, LS 디럭스 팩, LT, LT 디럭스팩,..."
9,chevrolet,볼트 (VOLT),[-],[1.5 EREV],class_name_examples=- | level_name_examples=1....
10,chevrolet,스파크,"[L, LS, LS 스타, LS 플러스, LT, LT 스페셜 에디션, 비트 에디션,...","[1.0, 1.0 LPGi, 1.0 S]","class_name_examples=L, LS, LS 스타, LS 플러스, LT, ..."
11,chevrolet,아베오,"[L 스타, LS 고급형, LT 스포츠, LT 최고급형, 스타일, 퍼펙트 블랙, L...","[1.4 터보, 1.4 터보 해치백, 1.6, 1.6 해치백]","class_name_examples=L 스타, LS 고급형, LT 스포츠, LT 최..."
12,chevrolet,어메이징 뉴 크루즈,"[LT 디럭스팩, LTZ, 프레셜 에디션 퍼펙트 블랙, LS, LT, 퍼펙트 블랙]","[1.4 터보, 1.4 터보 5도어, 1.6 디젤, 1.8, 1.8 5도어, 2.0...","class_name_examples=LT 디럭스팩, LTZ, 프레셜 에디션 퍼펙트 ..."
13,chevrolet,올 뉴 말리부,"[LS, LS 디럭스, LT, LT 디럭스, LTZ, LTZ 퍼펙트 블랙, LTZ ...","[1.5 터보, 1.8 HEV, 2.0 터보]","class_name_examples=LS, LS 디럭스, LT, LT 디럭스, LT..."
14,chevrolet,올 뉴 카마로 SS,"[-, 볼케이노 레드]",[6.2 V8],"class_name_examples=-, 볼케이노 레드 | level_name_ex..."
15,chevrolet,올 뉴 콜로라도,[Z71],[2.7 가솔린],class_name_examples=Z71 | level_name_examples=...
16,chevrolet,올 뉴 크루즈,"[LS, LT, LT 디럭스, LTZ, LTZ 디럭스]","[1.4 터보, 1.6 디젤]","class_name_examples=LS, LT, LT 디럭스, LTZ, LTZ 디..."
17,chevrolet,올란도,"[LS 고급형, LT 세이프티, LT 컨비니언스, LT 프리미엄, LTZ 세이프티,...","[1.6 디젤, 2.0 LPGi, 2.0 LPGi (랜터카용), 2.0 LPGi (...","class_name_examples=LS 고급형, LT 세이프티, LT 컨비니언스,..."
18,chevrolet,이쿼녹스,"[LS, LT, LT 익스클루시브, LT 플러스, LT 플러스 익스클루시브, 퍼펙트...","[1.6 디젤, 1.6 디젤 AWD]","class_name_examples=LS, LT, LT 익스클루시브, LT 플러스,..."
19,chevrolet,임팔라,"[LT, LTZ, 미드나이트 블랙, 프리미어]","[2.5, 3.6]","class_name_examples=LT, LTZ, 미드나이트 블랙, 프리미어 | ..."
20,chevrolet,카마로,"[-, RS]",[3.6 V6],"class_name_examples=-, RS | level_name_example..."
21,chevrolet,캡티바,"[LS, LS 디럭스팩, LS 프리미엄, LT, LT 디럭스팩, LT 프리미엄, L...","[2.0 디젤 2WD, 2.2 디젤 2WD, 2.2 디젤 4WD, 2.4 가솔린]","class_name_examples=LS, LS 디럭스팩, LS 프리미엄, LT, ..."
22,chevrolet,콜로라도,"[익스트림, 익스트림-X, 익스트림-X 사이드 레일, 익스트림-X 스포츠 바]","[3.6 V6, 3.6 V6 4WD]","class_name_examples=익스트림, 익스트림-X, 익스트림-X 사이드 레..."
23,chevrolet,콜벳,[-],[6.2 V8],class_name_examples=- | level_name_examples=6....
24,chevrolet,크루즈,"[LT 플러스 래더팩, LTZ 플러스, LTZ 플러스 더 퍼펙트 블랙, LTZ 플러...","[1.4 터보, 1.4 터보 5도어, 1.6, 1.8, 1.8 5도어, 2.0 디젤...","class_name_examples=LT 플러스 래더팩, LTZ 플러스, LTZ 플..."
25,chevrolet,타호,"[다크 나이트, 하이 컨트리]",[6.2 4WD],"class_name_examples=다크 나이트, 하이 컨트리 | level_nam..."
26,chevrolet,트래버스,"[LT 레더, LT 레더 프리미엄, RS, 레드라인, 프리미어]",[3.6 V6],"class_name_examples=LT 레더, LT 레더 프리미엄, RS, 레드라..."
27,chevrolet,트랙스,"[LS, LS 디럭스 패키지, LT, LT 디럭스, LT 레더 패키지, LTZ, 퍼...","[1.4 가솔린, 1.6 디젤]","class_name_examples=LS, LS 디럭스 패키지, LT, LT 디럭스..."
28,chevrolet,트랙스 크로스오버,"[LS, LT, RS, RS 미드나잇 에디션, 레드라인, 액티브]",[1.2 가솔린 터보],"class_name_examples=LS, LT, RS, RS 미드나잇 에디션, 레..."
29,chevrolet,트레일블레이저,"[LS, LT, RS, 액티브, 프리미어]","[1.2 터보 2WD, 1.3 터보 2WD, 1.3 터보 AWD]","class_name_examples=LS, LT, RS, 액티브, 프리미어 | le..."

(PosixPath('/Users/iwonbin/workspace/Study/boot/SKN28-1st-4team/data_collection/raw/models_cohort/cohort_generation/data/model_category_mapping_requests.csv'),
 (267, 5))

## Initialize or Resume Mapping Table

기존 `model_category_mapping_table.csv`가 있으면 불러오고, 이미 매핑된 `brand + model_name`은 스킵한다.
필요하면 `RESET_MAPPING_TABLE = True`로 두고 완전히 새로 시작할 수 있다.

In [8]:
mapping_table_path = DATA_PATH.parent / "model_category_mapping_table.csv"
RESET_MAPPING_TABLE = False

if mapping_table_path.exists() and not RESET_MAPPING_TABLE:
    mapping_table_df = load_mapping_table(mapping_table_path)
else:
    mapping_table_df = pd.DataFrame(columns=["brand", "model_name", "major_category", "search_used", "note"])

pending_requests_df = get_pending_requests(requests_df, mapping_table_df)

print("existing mapping rows:", len(mapping_table_df))
print("pending requests:", len(pending_requests_df))

with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(mapping_table_df)
display(pending_requests_df.head(20))

existing mapping rows: 6
pending requests: 261

,brand,model_name,major_category,search_used,note
0,chevrolet,더 넥스트 스파크,hatchback,False,"Derived from Chevrolet Spark, a subcompact hat..."
1,chevrolet,더 뉴 말리부,sedan,False,NaN
2,chevrolet,더 뉴 스파크,hatchback,True,The user wants mapping only. We have answer.
3,chevrolet,더 뉴 아베오,hatchback,False,"Based on class trims (L, LS, LT) and level nam..."
4,chevrolet,더 뉴 카마로 SS,coupe_convertible,False,"Chevrolet Camaro SS is a 2-door coupe, categor..."
5,chevrolet,더 뉴 트랙스,suv,False,NaN

,brand,model_name,class_name_examples,level_name_examples,context_summary
6,chevrolet,더 뉴 트레일블레이저,"[LT, RS, 액티브, 프리미어]","[1.3 터보 2WD, 1.3 터보 AWD]","class_name_examples=LT, RS, 액티브, 프리미어 | level_..."
7,chevrolet,리얼 뉴 콜로라도,"[익스트림, Z71-X, Z71-X 미드나잇, 익스트림-X]","[3.6 V6, 3.6 V6 4WD]","class_name_examples=익스트림, Z71-X, Z71-X 미드나잇, 익..."
8,chevrolet,말리부,"[LS, LS 디럭스 팩, LT, LT 디럭스팩, LTZ, LTZ 디럭스팩(블랙휠)...","[2.0, 2.0 디젤, 2.4]","class_name_examples=LS, LS 디럭스 팩, LT, LT 디럭스팩,..."
9,chevrolet,볼트 (VOLT),[-],[1.5 EREV],class_name_examples=- | level_name_examples=1....
10,chevrolet,스파크,"[L, LS, LS 스타, LS 플러스, LT, LT 스페셜 에디션, 비트 에디션,...","[1.0, 1.0 LPGi, 1.0 S]","class_name_examples=L, LS, LS 스타, LS 플러스, LT, ..."
11,chevrolet,아베오,"[L 스타, LS 고급형, LT 스포츠, LT 최고급형, 스타일, 퍼펙트 블랙, L...","[1.4 터보, 1.4 터보 해치백, 1.6, 1.6 해치백]","class_name_examples=L 스타, LS 고급형, LT 스포츠, LT 최..."
12,chevrolet,어메이징 뉴 크루즈,"[LT 디럭스팩, LTZ, 프레셜 에디션 퍼펙트 블랙, LS, LT, 퍼펙트 블랙]","[1.4 터보, 1.4 터보 5도어, 1.6 디젤, 1.8, 1.8 5도어, 2.0...","class_name_examples=LT 디럭스팩, LTZ, 프레셜 에디션 퍼펙트 ..."
13,chevrolet,올 뉴 말리부,"[LS, LS 디럭스, LT, LT 디럭스, LTZ, LTZ 퍼펙트 블랙, LTZ ...","[1.5 터보, 1.8 HEV, 2.0 터보]","class_name_examples=LS, LS 디럭스, LT, LT 디럭스, LT..."
14,chevrolet,올 뉴 카마로 SS,"[-, 볼케이노 레드]",[6.2 V8],"class_name_examples=-, 볼케이노 레드 | level_name_ex..."
15,chevrolet,올 뉴 콜로라도,[Z71],[2.7 가솔린],class_name_examples=Z71 | level_name_examples=...
16,chevrolet,올 뉴 크루즈,"[LS, LT, LT 디럭스, LTZ, LTZ 디럭스]","[1.4 터보, 1.6 디젤]","class_name_examples=LS, LT, LT 디럭스, LTZ, LTZ 디..."
17,chevrolet,올란도,"[LS 고급형, LT 세이프티, LT 컨비니언스, LT 프리미엄, LTZ 세이프티,...","[1.6 디젤, 2.0 LPGi, 2.0 LPGi (랜터카용), 2.0 LPGi (...","class_name_examples=LS 고급형, LT 세이프티, LT 컨비니언스,..."
18,chevrolet,이쿼녹스,"[LS, LT, LT 익스클루시브, LT 플러스, LT 플러스 익스클루시브, 퍼펙트...","[1.6 디젤, 1.6 디젤 AWD]","class_name_examples=LS, LT, LT 익스클루시브, LT 플러스,..."
19,chevrolet,임팔라,"[LT, LTZ, 미드나이트 블랙, 프리미어]","[2.5, 3.6]","class_name_examples=LT, LTZ, 미드나이트 블랙, 프리미어 | ..."
20,chevrolet,카마로,"[-, RS]",[3.6 V6],"class_name_examples=-, RS | level_name_example..."
21,chevrolet,캡티바,"[LS, LS 디럭스팩, LS 프리미엄, LT, LT 디럭스팩, LT 프리미엄, L...","[2.0 디젤 2WD, 2.2 디젤 2WD, 2.2 디젤 4WD, 2.4 가솔린]","class_name_examples=LS, LS 디럭스팩, LS 프리미엄, LT, ..."
22,chevrolet,콜로라도,"[익스트림, 익스트림-X, 익스트림-X 사이드 레일, 익스트림-X 스포츠 바]","[3.6 V6, 3.6 V6 4WD]","class_name_examples=익스트림, 익스트림-X, 익스트림-X 사이드 레..."
23,chevrolet,콜벳,[-],[6.2 V8],class_name_examples=- | level_name_examples=6....
24,chevrolet,크루즈,"[LT 플러스 래더팩, LTZ 플러스, LTZ 플러스 더 퍼펙트 블랙, LTZ 플러...","[1.4 터보, 1.4 터보 5도어, 1.6, 1.8, 1.8 5도어, 2.0 디젤...","class_name_examples=LT 플러스 래더팩, LTZ 플러스, LTZ 플..."
25,chevrolet,타호,"[다크 나이트, 하이 컨트리]",[6.2 4WD],"class_name_examples=다크 나이트, 하이 컨트리 | level_nam..."

## Run Category Agent in Batches

한 번에 전부 돌리지 않고 batch 단위로 호출한다.
각 batch가 끝날 때마다 CSV를 저장하므로 오래 걸려도 중간 진행분을 유지할 수 있다.

In [9]:
RUN_AGENT = True
RUN_LIMIT = None  # 예: 40
BATCH_SIZE = 20

if not is_agent_env_ready():
    print('OPENROUTER_API_KEY is missing. Fill cohort_generation/.env first.')
elif not RUN_AGENT:
    print('Set RUN_AGENT = True to execute the category mapping agent.')
else:
    config = CohortAgentConfig.from_env()
    rows_to_run = pending_requests_df.copy()
    if RUN_LIMIT is not None:
        rows_to_run = rows_to_run.head(RUN_LIMIT).copy()

    total_rows = len(rows_to_run)
    appended_batches = []

    for batch_index, start in enumerate(range(0, total_rows, BATCH_SIZE), start=1):
        batch_df = rows_to_run.iloc[start : start + BATCH_SIZE].copy()
        batch_rows = []
        print(f"batch {batch_index}: rows {start + 1}-{start + len(batch_df)} / {total_rows}")

        for request in dataframe_to_mapping_inputs(batch_df):
            result = run_category_mapping_sync(request, config)
            batch_rows.append(result.model_dump(mode="json"))

        if batch_rows:
            batch_result_df = pd.DataFrame(batch_rows)
            appended_batches.append(batch_result_df)
            mapping_table_df = pd.concat([mapping_table_df, batch_result_df], ignore_index=True)
            mapping_table_df = mapping_table_df.drop_duplicates(subset=["brand", "model_name"], keep="last")
            mapping_table_df.to_csv(mapping_table_path, index=False)
            print(f"saved mapping rows: {len(mapping_table_df)}")

    if appended_batches:
        appended_df = pd.concat(appended_batches, ignore_index=True)
        display(appended_df)

    with pd.option_context("display.max_rows", None, "display.max_columns", None):
        display(mapping_table_df)

    mapping_table_path

debug: model name : openai/gpt-5.2-chat
batch 1: rows 1-20 / 261
saved mapping rows: 26
batch 2: rows 21-40 / 261
saved mapping rows: 46
batch 3: rows 41-60 / 261
saved mapping rows: 66
batch 4: rows 61-80 / 261
saved mapping rows: 86
batch 5: rows 81-100 / 261
saved mapping rows: 106
batch 6: rows 101-120 / 261
saved mapping rows: 126
batch 7: rows 121-140 / 261
saved mapping rows: 146
batch 8: rows 141-160 / 261
saved mapping rows: 166
batch 9: rows 161-180 / 261
saved mapping rows: 186
batch 10: rows 181-200 / 261
saved mapping rows: 206
batch 11: rows 201-220 / 261
saved mapping rows: 226
batch 12: rows 221-240 / 261
saved mapping rows: 246
batch 13: rows 241-260 / 261
saved mapping rows: 266
batch 14: rows 261-261 / 261
saved mapping rows: 267

,brand,model_name,major_category,search_used,note
0,chevrolet,더 뉴 트레일블레이저,suv,False,Chevrolet Trailblazer is sold in Korea as a co...
1,chevrolet,리얼 뉴 콜로라도,truck,False,쉐보레 콜로라도는 중형 픽업트럭 모델
2,chevrolet,말리부,sedan,False,Chevrolet Malibu is a midsize 4-door sedan.
3,chevrolet,볼트 (VOLT),hatchback,False,Chevrolet Volt (EREV) is a 5-door compact hatc...
4,chevrolet,스파크,hatchback,False,Chevrolet Spark is a subcompact 5-door hatchba...
...,...,...,...,...,...
256,renault,마스터,van,False,"르노 마스터는 대형 상용 밴/미니버스 기반 모델로 13·15인승, 밴, 캠핑카 등 ..."
257,renault,올 뉴 SM7,sedan,False,None
258,renault,캡처,suv,False,르노 캡처는 B세그먼트 소형 SUV(크로스오버)로 공식 판매됨
259,renault,클리오,hatchback,False,르노 클리오는 전 세계적으로 판매된 소형 5도어 해치백 모델
260,renault,필랑트,sedan,True,"국내 자료 및 모델 설명에서 중대형 하이브리드 세단으로 소개됨 (차체 길이 약 4,..."

,brand,model_name,major_category,search_used,note
0,chevrolet,더 넥스트 스파크,hatchback,False,"Derived from Chevrolet Spark, a subcompact hat..."
1,chevrolet,더 뉴 말리부,sedan,False,NaN
2,chevrolet,더 뉴 스파크,hatchback,True,The user wants mapping only. We have answer.
3,chevrolet,더 뉴 아베오,hatchback,False,"Based on class trims (L, LS, LT) and level nam..."
4,chevrolet,더 뉴 카마로 SS,coupe_convertible,False,"Chevrolet Camaro SS is a 2-door coupe, categor..."
5,chevrolet,더 뉴 트랙스,suv,False,NaN
6,chevrolet,더 뉴 트레일블레이저,suv,False,Chevrolet Trailblazer is sold in Korea as a co...
7,chevrolet,리얼 뉴 콜로라도,truck,False,쉐보레 콜로라도는 중형 픽업트럭 모델
8,chevrolet,말리부,sedan,False,Chevrolet Malibu is a midsize 4-door sedan.
9,chevrolet,볼트 (VOLT),hatchback,False,Chevrolet Volt (EREV) is a 5-door compact hatc...
10,chevrolet,스파크,hatchback,False,Chevrolet Spark is a subcompact 5-door hatchba...
11,chevrolet,아베오,unknown,True,공식·참고 자료에서 아베오는 소형 세단과 해치백 두 가지 차체로 모두 판매됨; 단일...
12,chevrolet,어메이징 뉴 크루즈,sedan,True,공식·위키 자료에서 크루즈는 준중형 세단으로 분류됨(국내에 5도어 해치백도 있었으나...
13,chevrolet,올 뉴 말리부,sedan,False,쉐보레 말리부는 중형급 4도어 세단 모델
14,chevrolet,올 뉴 카마로 SS,coupe_convertible,False,Camaro is a two-door sports/muscle coupe; SS i...
15,chevrolet,올 뉴 콜로라도,truck,False,Chevrolet Colorado is a midsize pickup truck m...
16,chevrolet,올 뉴 크루즈,sedan,False,국내 판매된 올 뉴 크루즈는 4도어 중형 세단
17,chevrolet,올란도,van,False,쉐보레 올란도는 5~7인승 MPV(다목적 미니밴)로 판매된 모델
18,chevrolet,이쿼녹스,suv,False,쉐보레 이쿼녹스는 공식적으로 컴팩트 SUV 모델
19,chevrolet,임팔라,sedan,False,Chevrolet Impala is a full-size sedan model.
20,chevrolet,카마로,coupe_convertible,False,Chevrolet Camaro is a two-door sports coupe/co...
21,chevrolet,캡티바,suv,False,GM코리아에서 판매된 캡티바는 중형급 SUV 모델로 분류됨
22,chevrolet,콜로라도,truck,False,쉐보레 콜로라도는 중형 픽업트럭 모델
23,chevrolet,콜벳,coupe_convertible,False,Chevrolet Corvette is a sports car offered as ...
24,chevrolet,크루즈,sedan,False,한국 쉐보레 크루즈는 주력 차체가 준중형 세단이며 5도어 해치백도 병행 판매됨; 모...
25,chevrolet,타호,suv,False,쉐보레 타호는 대표적인 풀사이즈 SUV 모델
26,chevrolet,트래버스,suv,False,쉐보레 트래버스는 3열 중대형 SUV 모델
27,chevrolet,트랙스,suv,False,쉐보레 트랙스는 공식적으로 소형 SUV(서브컴팩트 SUV)로 판매된 모델
28,chevrolet,트랙스 크로스오버,suv,False,쉐보레 트랙스 크로스오버는 소형 SUV(크로스오버) 모델
29,chevrolet,트레일블레이저,suv,False,한국 GM에서 소형 SUV(크로스오버)로 판매되는 트레일블레이저 모델
30,hyundai,LF쏘나타,sedan,False,"LF쏘나타는 현대 쏘나타 LF 세대로, 중형 세단 모델"
31,hyundai,LF쏘나타 하이브리드,sedan,False,쏘나타는 현대의 중형 세단 라인업이며 하이브리드도 동일한 세단 차체
32,hyundai,YF쏘나타,sedan,False,YF 쏘나타는 현대자동차의 중형 세단 모델
33,hyundai,i20,hatchback,False,Hyundai i20 is a subcompact 5-door hatchback m...
34,hyundai,i30,hatchback,False,Hyundai i30 is a compact C-segment hatchback m...
35,hyundai,i30 PD,hatchback,False,Hyundai i30 (PD generation) is a C-segment 5-d...
36,hyundai,i30CW,wagon,False,i30 CW is the station wagon (estate) variant o...
37,hyundai,i40,wagon,False,i40 is sold as i40 Wagon (Tourer); level names...
38,hyundai,i40 살룬,sedan,False,‘살룬(Saloon)’ denotes the sedan body of the Hyu...
39,hyundai,그랜드스타렉스,van,False,현대 그랜드 스타렉스는 승합·밴 기반의 대형 밴/미니버스 모델
40,hyundai,그랜저HG,sedan,False,그랜저 HG는 현대의 준대형 세단 모델
41,hyundai,그랜저HG 하이브리드,sedan,False,그랜저(HG)는 현대의 대형 세단 라인업이며 하이브리드 트림도 차체 형태는 세단
42,hyundai,그랜저IG,sedan,False,현대 그랜저 IG는 대형 세단 모델
43,hyundai,그랜저IG 하이브리드,sedan,False,그랜저(IG)는 현대의 대형 세단 모델이며 하이브리드도 동일한 세단 차체
44,hyundai,뉴 i30,hatchback,False,Hyundai i30 is a compact hatchback model
45,hyundai,뉴 에쿠스,sedan,False,현대차 플래그십 대형 럭셔리 세단(리무진 트림 포함하나 기본 차체는 세단)
46,hyundai,뉴 카운티,bus,True,Hyundai New County is a mid-size commercial bu...
47,hyundai,뉴 투싼ix,suv,False,Hyundai Tucson ix (뉴 투싼ix) is a compact SUV model
48,hyundai,더 뉴 i30,hatchback,False,None
49,hyundai,더 뉴 i40,sedan,False,현대 i40는 국내에서 중형 세단으로 판매됨(왜건은 별도 i40 왜건으로 구분)
50,hyundai,더 뉴 i40 살룬,sedan,False,i40 살룬은 i40의 세단형(살룬) 모델
51,hyundai,더 뉴 그랜드스타렉스,van,False,그랜드스타렉스는 현대의 대형 승합/밴 모델로 3~15인승 밴·미니버스 기반
52,hyundai,더 뉴 그랜저,sedan,False,현대 그랜저는 대표적인 대형 세단 모델
53,hyundai,더 뉴 그랜저 하이브리드,sedan,False,그랜저는 현대의 대표적인 대형 세단 모델이며 하이브리드도 동일한 세단 차체
54,hyundai,더 뉴 맥스크루즈,suv,False,현대 맥스크루즈는 싼타페 기반의 중형 SUV 모델
55,hyundai,더 뉴 벨로스터,hatchback,False,현대 벨로스터는 비대칭 도어 구조의 컴팩트 해치백 모델
56,hyundai,더 뉴 스타리아,van,False,현대 스타리아는 다인승 MPV/미니버스 형태의 대형 밴 모델
57,hyundai,더 뉴 싼타페,suv,False,현대 싼타페는 중형 SUV로 판매되는 모델
58,hyundai,더 뉴 싼타페 하이브리드,suv,False,싼타페는 현대의 대표적인 중형 SUV 모델이며 하이브리드 여부와 무관하게 차체 유형...
59,hyundai,더 뉴 아반떼,sedan,False,현대 아반떼(Elantra)로 알려진 준중형 세단
60,hyundai,더 뉴 아반떼 [CN7],sedan,False,아반떼(CN7)는 현대자동차의 준중형 세단 모델
61,hyundai,더 뉴 아반떼 하이브리드 [CN7],sedan,False,아반떼(CN7)는 현대의 준중형 4도어 세단이며 하이브리드 트림도 동일한 세단 바디
62,hyundai,더 뉴 아반떼AD,sedan,False,아반떼(AD)는 현대의 준중형 4도어 세단 모델
63,hyundai,더 뉴 아이오닉 플러그인,hatchback,False,아이오닉 플러그인 하이브리드는 기존 아이오닉과 동일한 5도어 해치백 바디
64,hyundai,더 뉴 아이오닉 하이브리드,hatchback,False,Hyundai Ioniq Hybrid (original Ioniq) is a 5-d...
65,hyundai,더 뉴 제네시스 쿠페,coupe_convertible,False,제네시스 쿠페는 현대의 2도어 스포츠 쿠페 모델
66,hyundai,더 뉴 캐스퍼,suv,False,현대 캐스퍼는 경형 SUV(소형 크로스오버)로 공식 분류됨
67,hyundai,더 뉴 코나,suv,False,현대 코나(KONA)는 공식적으로 소형 SUV로 분류됨
68,hyundai,더 뉴 코나 하이브리드,suv,False,코나는 현대의 소형 크로스오버 SUV 모델이며 하이브리드 트림도 동일한 차체 유형
69,hyundai,더 뉴 투싼,suv,False,Hyundai Tucson is a compact SUV; trims and dri...
70,hyundai,더 뉴 투싼 하이브리드,suv,False,투싼은 현대의 대표적인 준중형 SUV 모델
71,hyundai,더 뉴 팰리세이드,suv,False,현대 팰리세이드는 대형 3열 SUV 모델
72,hyundai,디 올 뉴 그랜저,sedan,False,현대 그랜저는 브랜드의 대표적인 대형 세단 모델
73,hyundai,디 올 뉴 그랜저 하이브리드,sedan,False,"그랜저는 현대의 대형 세단 라인업으로, 하이브리드 트림도 동일한 세단 바디"
74,hyundai,디 올 뉴 싼타페,suv,False,싼타페는 현대자동차의 중형 SUV 모델
75,hyundai,디 올 뉴 싼타페 하이브리드,suv,False,싼타페는 현대의 중형 SUV 모델이며 하이브리드 여부나 트림은 차체 유형에 영향 없음
76,hyundai,디 올 뉴 코나,suv,False,현대 코나는 공식적으로 소형 SUV(크로스오버) 모델
77,hyundai,디 올 뉴 코나 하이브리드,suv,False,현대 코나 라인업의 하이브리드 소형 SUV
78,hyundai,디 올 뉴 투싼,suv,False,투싼은 현대의 대표적인 준중형 SUV 모델
79,hyundai,디 올 뉴 투싼 하이브리드,suv,False,투싼(Tucson)은 현대의 대표적인 준중형 SUV 모델이며 하이브리드 여부와 트림...
80,hyundai,디 올 뉴 팰리세이드,suv,False,현대자동차의 대형 SUV 모델
81,hyundai,맥스크루즈,suv,False,Hyundai 맥스크루즈(Maxcruz)는 대형화된 산타페 기반의 중형 SUV 모델
82,hyundai,베뉴,suv,False,현대 소형 SUV (Venue)
83,hyundai,베라크루즈,suv,False,현대 베라크루즈(Veracruz)는 중대형 SUV 모델
84,hyundai,벨로스터,hatchback,False,현대 벨로스터는 3도어 구조의 컴팩트 해치백으로 공식적으로도 해치백 모델로 분류됨
85,hyundai,벨로스터 N,hatchback,False,Veloster N is the high-performance trim of the...
86,hyundai,벨로스터 [JS],hatchback,False,현대 벨로스터는 3도어 구조의 컴팩트 해치백으로 공식 분류됨
87,hyundai,스타리아,van,False,Hyundai Staria is a large MPV/van platform (pa...
88,hyundai,싼타페 더 프라임,suv,False,현대 싼타페는 중형 SUV 모델
89,hyundai,싼타페 더스타일,suv,False,싼타페는 현대자동차의 중형 SUV 모델이며 '더스타일'은 해당 세대의 페이스리프트 명칭
90,hyundai,싼타페CM,suv,False,싼타페(CM)는 현대자동차의 중형 SUV 모델
91,hyundai,싼타페DM,suv,False,현대 싼타페(DM)는 중형 SUV 모델
92,hyundai,싼타페TM,suv,False,현대 싼타페(TM)는 중형 SUV 모델
93,hyundai,쏘나타 DN8,sedan,False,현대 쏘나타 DN8은 중형 세단 모델
94,hyundai,쏘나타 뉴 라이즈,sedan,False,현대 쏘나타 뉴 라이즈는 중형 세단 모델
95,hyundai,쏘나타 뉴 라이즈 하이브리드,sedan,False,"쏘나타(Sonata)는 현대의 중형 세단이며, 하이브리드/플러그인 하이브리드 트림도..."
96,hyundai,쏘나타 더 브릴리언트,sedan,False,쏘나타(The Brilliant)는 현대자동차의 중형 세단 모델
97,hyundai,쏘나타 디 엣지,sedan,False,"현대 쏘나타의 최신 페이스리프트 모델로, 중형 세단"
98,hyundai,쏘나타 디 엣지 하이브리드,sedan,False,쏘나타(The Edge) 하이브리드는 현대 쏘나타 중형 세단의 하이브리드 파워트레인 모델
99,hyundai,쏘나타 하이브리드,sedan,False,쏘나타 하이브리드는 현대 쏘나타 기반의 중형 세단 하이브리드 모델
100,hyundai,쏘나타 하이브리드 [DN8],sedan,False,쏘나타(DN8)는 현대자동차의 중형 세단 모델이며 하이브리드 파워트레인도 동일한 세...
101,hyundai,쏠라티,bus,True,"현대 쏠라티는 공식적으로 대형 미니버스/소형 버스로 분류되며 15~23인승, 어린이..."
102,hyundai,아반떼 LPi 하이브리드,sedan,False,아반떼(엘란트라)는 연료·파워트레인과 무관하게 기본 차체가 준중형 세단
103,hyundai,아반떼 N,sedan,False,아반떼(Elantra) 기반 고성능 N 트림으로 기본 차체는 컴팩트 세단
104,hyundai,아반떼 쿠페,coupe_convertible,False,아반떼의 2도어 쿠페 모델
105,hyundai,아반떼AD,sedan,False,아반떼(Elantra) AD 세대는 현대의 대표적인 준중형 4도어 세단
106,hyundai,아반떼MD,sedan,False,현대 아반떼 MD는 국내 판매된 준중형 4도어 세단 모델
107,hyundai,아슬란,sedan,False,국내 출시된 현대 아슬란은 대형급 4도어 세단 모델
108,hyundai,아이오닉 플러그인,hatchback,False,Hyundai Ioniq Plug-in Hybrid is a 5-door compa...
109,hyundai,아이오닉 하이브리드,hatchback,False,현대 아이오닉(HEV)은 5도어 해치백/리프트백 형태의 친환경 모델
110,hyundai,엑센트 (신형),sedan,False,"현대 엑센트는 기본적으로 소형 세단 모델이며, 위트(WIT)는 해치백 파생형"
111,hyundai,올 뉴 아반떼 [CN7],sedan,False,현대 아반떼(CN7)는 전형적인 준중형 세단
112,hyundai,올 뉴 아반떼 하이브리드 [CN7],sedan,False,아반떼(CN7)는 현대의 준중형 세단 라인업
113,hyundai,올 뉴 투싼,suv,False,현대 투싼은 제조사 공식 분류상 준중형 SUV 모델
114,hyundai,제네시스,sedan,False,Hyundai Genesis (BH series) is a full-size lux...
115,hyundai,제네시스 DH,sedan,False,현대 제네시스 DH는 대형 럭셔리 세단 모델
116,hyundai,제네시스 쿠페,coupe_convertible,False,Hyundai Genesis Coupe is a 2-door sports coupe...
117,hyundai,캐스퍼,suv,False,현대 캐스퍼는 국내에서 경형 SUV(마이크로 SUV)로 공식 분류됨
118,hyundai,코나,suv,False,현대 코나는 제조사 기준 소형 SUV로 판매되는 모델
119,hyundai,코나 N,suv,False,"코나 N은 현대 코나 기반의 고성능 트림으로, 기본 차체는 소형 SUV(크로스오버)"
120,hyundai,코나 하이브리드,suv,False,코나는 현대의 소형 SUV(크로스오버) 모델
121,hyundai,투싼ix,suv,False,현대 투싼(ix)으로 판매된 컴팩트 SUV 모델
122,hyundai,팰리세이드,suv,False,현대자동차 공식 대형 SUV 모델
123,hyundai,포레스트,van,True,"현대 포레스트는 포터Ⅱ 초장축 기반으로 제작된 모터홈 캠핑카로, 공식 자료에서 캠핑..."
124,hyundai,포터2,truck,False,현대자동차의 1톤급 경상용 픽업 트럭(포터 II)
125,kgm,G4 렉스턴,suv,False,G4 렉스턴은 바디온프레임 기반의 대형 SUV 모델
126,kgm,뉴 로디우스,van,False,"쌍용 로디우스 기반 대형 MPV/미니밴, 9~11인승 구성"
127,kgm,뉴 스타일 코란도 C,suv,False,코란도 C는 쌍용/현 KGM의 대표적인 컴팩트 SUV 모델
128,kgm,뉴 체어맨W,sedan,False,KGM(구 쌍용) 플래그십 대형 럭셔리 세단 모델
129,kgm,뉴 코란도 C,suv,False,Korando C is a compact SUV model (formerly Ssa...
130,kgm,뉴카이런,suv,False,구 쌍용자동차(현 KG모빌리티) 카이런으로 판매된 중형 SUV 모델
131,kgm,더 뉴 렉스턴 스포츠,truck,False,렉스턴 스포츠는 적재함을 가진 중형 픽업 트럭 모델
132,kgm,더 뉴 렉스턴 스포츠 칸,truck,False,렉스턴 스포츠 칸은 적재함을 갖춘 픽업 트럭 모델
133,kgm,더 뉴 코란도 스포츠,truck,False,코란도 스포츠는 적재함을 갖춘 픽업트럭 모델
134,kgm,렉스턴 뉴 아레나,suv,False,KGM(구 쌍용) 렉스턴 라인업의 대형 프레임 기반 SUV
135,kgm,렉스턴 스포츠,truck,False,렉스턴 스포츠는 쌍용/KGM의 픽업트럭 모델
136,kgm,렉스턴 스포츠 칸,truck,False,렉스턴 스포츠의 적재함을 확장한 픽업트럭(상용·레저용) 모델
137,kgm,렉스턴W,suv,False,쌍용(현 KGM) 렉스턴 W는 프레임 기반 중대형 SUV 모델
138,kgm,무쏘,suv,False,쌍용 무쏘(현 KGM)는 바디온프레임 기반의 중형 SUV 모델
139,kgm,무쏘 스포츠,truck,False,쌍용(현 KGM) 무쏘 스포츠는 적재함을 갖춘 픽업트럭 모델
140,kgm,베리 뉴 티볼리,suv,False,티볼리는 KG모빌리티(구 쌍용)의 소형 SUV 모델
141,kgm,뷰티풀 코란도,suv,False,쌍용/ KGM 코란도의 후속으로 판매된 컴팩트 SUV 모델
142,kgm,슈퍼 렉스턴,suv,False,쌍용(현 KGM) 렉스턴 기반의 바디온프레임 대형 SUV
143,kgm,액티언 2세대,suv,True,공식·참고 자료에서 2세대 액티언은 쿠페형 SUV로 소개됨
144,kgm,올 뉴 렉스턴,suv,False,KG모빌리티(구 쌍용) 플래그십 바디온프레임 대형 SUV 모델
145,kgm,체어맨H 뉴 클래식,sedan,False,쌍용(현 KGM) 체어맨 H는 대형 플래그십 럭셔리 세단 모델
146,kgm,코란도 C,suv,False,쌍용(현 KGM) 코란도 C는 C세그먼트 컴팩트 SUV로 판매됨
147,kgm,코란도 스포츠,truck,False,쌍용(현 KGM) 코란도 스포츠는 적재함을 가진 픽업 트럭 모델
148,kgm,코란도 투리스모,van,False,9·11인승 대형 MPV로 판매된 코란도 투리스모는 미니밴/밴 계열 모델
149,kgm,토레스,suv,False,KGM(구 쌍용) 토레스는 중형 SUV 모델
150,kgm,티볼리,suv,False,국내에서 소형 SUV로 잘 알려진 KGM(구 쌍용) 티볼리 모델
151,kgm,티볼리 아머,suv,False,쌍용(현 KGM) 티볼리 아머는 소형 SUV 모델
152,kgm,티볼리 에어,suv,False,티볼리의 롱바디 파생 모델로 분류상 소형 SUV
153,kia,K3,sedan,False,Kia K3 is a compact sedan; trims and engines l...
154,kia,K3 쿱,coupe_convertible,False,K3의 2도어 쿠페(쿱) 바디 모델
155,kia,K5,sedan,False,Kia K5 (Optima) is a midsize sedan across all ...
156,kia,K5 2세대,sedan,False,Kia K5 2세대는 중형 세단으로 공식 모델 포지션이 세단임
157,kia,K5 3세대,sedan,False,Kia K5 3세대는 중형 4도어 세단으로 공식 모델 포지션이 세단임
158,kia,K5 하이브리드,sedan,False,Kia K5 (Optima) is a midsize 4-door sedan; hyb...
159,kia,K5 하이브리드 2세대,sedan,False,Kia K5 (Optima) is a midsize sedan; hybrid pow...
160,kia,K5 하이브리드 3세대,sedan,False,Kia K5 (Optima) is a midsize sedan; hybrid pow...
161,kia,K7,sedan,False,Kia K7 is a large/mid-full size passenger seda...
162,kia,K7 프리미어,sedan,False,기아 K7(프리미어)는 국내 준대형 4도어 세단 모델
163,kia,K7 프리미어 하이브리드,sedan,False,Kia K7 (Cadenza) is a large sedan; hybrid powe...
164,kia,K7 하이브리드,sedan,False,Kia K7(카덴자)는 준대형 세단이며 하이브리드도 동일한 세단 차체
165,kia,K8,sedan,False,기아 공식 대형 세단(K7 후속 모델)
166,kia,K8 하이브리드,sedan,False,Kia K8 is a large sedan; hybrid powertrain doe...
167,kia,K9,sedan,False,Kia K9 is a flagship full-size luxury sedan (k...
168,kia,뉴 쏘렌토R,suv,False,쏘렌토 R은 기아의 중형 SUV 모델
169,kia,뉴 카니발 R,van,False,카니발은 기아의 대표적인 미니밴(MPV) 모델
170,kia,뉴 페이스 카렌스,van,False,카렌스는 기아의 MPV/미니밴 계열 패밀리 차량으로 세단이나 SUV가 아닌 밴(사람...
171,kia,뉴모닝,hatchback,False,기아 모닝(뉴모닝)은 경형 해치백으로 판매됨
172,kia,니로,suv,False,Kia Niro is marketed as a subcompact crossover...
173,kia,더 K9,sedan,False,기아의 플래그십 대형 럭셔리 세단 (K9/K900)
174,kia,더 뉴 K3,sedan,False,Kia K3 (Forte/Cerato) is a compact sedan; offi...
175,kia,더 뉴 K3 [2세대],sedan,False,K3 is primarily sold as a compact sedan in Kor...
176,kia,더 뉴 K3 쿱,coupe_convertible,False,K3의 2도어 쿠페(쿱) 바디 모델
177,kia,더 뉴 K5,sedan,False,Kia K5 is a midsize sedan; trims and LPi/turbo...
178,kia,더 뉴 K5 2세대,sedan,False,Kia K5 (Optima) 2세대는 중형 4도어 세단 모델
179,kia,더 뉴 K5 3세대,sedan,False,"Kia K5 (3세대, 더 뉴) is a midsize passenger sedan..."
180,kia,더 뉴 K5 하이브리드 2세대,sedan,False,K5(옵티마) 하이브리드는 중형 세단 모델
181,kia,더 뉴 K5 하이브리드 3세대,sedan,False,None
182,kia,더 뉴 K7,sedan,False,Kia K7 (Cadenza) is a mid-to-large executive s...
183,kia,더 뉴 K8,sedan,False,None
184,kia,더 뉴 K8 하이브리드,sedan,False,Kia K8 is a full-size/mid-large sedan; hybrid ...
185,kia,더 뉴 K9,sedan,False,기아 K9은 브랜드 플래그십 대형 세단 모델
186,kia,더 뉴 K9 [RJ],sedan,False,기아 플래그십 대형 럭셔리 세단 (K9/K900)
187,kia,더 뉴 기아 레이,hatchback,False,"기아 레이는 박스형 경차로 기본 차체는 해치백이며, 밴 트림이 있어도 모델 레벨 분..."
188,kia,더 뉴 니로,suv,False,기아 니로는 하이브리드/플러그인 하이브리드 기반의 소형 크로스오버 SUV 모델
189,kia,더 뉴 레이,van,True,Official and reference sources describe Kia Ra...
190,kia,더 뉴 모닝,hatchback,False,기아 모닝은 국내 경차급 5도어 해치백 모델
191,kia,더 뉴 모닝 [JA],hatchback,False,기아 모닝(JA)은 경형 5도어 해치백
192,kia,더 뉴 모하비,suv,False,기아 모하비는 프레임 바디 기반의 대형 SUV 모델
193,kia,더 뉴 봉고3,truck,False,기아 봉고3는 국내 경상용 픽업/트럭 모델
194,kia,더 뉴 셀토스,suv,False,Kia Seltos is a subcompact SUV; trims like X-L...
195,kia,더 뉴 스포티지R,suv,False,스포티지 R는 기아의 대표적인 컴팩트 SUV 모델
196,kia,더 뉴 쏘렌토,suv,False,쏘렌토는 기아의 중형 SUV 모델
197,kia,더 뉴 쏘렌토 4세대,suv,False,쏘렌토는 기아의 대표적인 중형 SUV 모델
198,kia,더 뉴 쏘렌토 4세대 하이브리드,suv,False,쏘렌토는 기아의 중형 SUV 모델
199,kia,더 뉴 쏘울,suv,False,기아 공식 분류에서 박스형 소형 SUV(크로스오버)로 판매됨
200,kia,더 뉴 카니발,van,False,카니발은 기아의 대표적인 미니밴(MPV) 모델로 다인승 중심의 밴 바디
201,kia,더 뉴 카니발 4세대,van,False,"카니발은 기아의 대표적인 대형 미니밴(다인승 RV) 모델로, 모든 트림이 밴/미니밴..."
202,kia,더 뉴 카렌스,van,False,카렌스는 기아의 컴팩트 MPV/미니밴(국내 RV) 모델
203,kia,더 뉴 프라이드,hatchback,True,"공식·중고차 자료에서 프라이드는 소형 해치백(5도어)으로 주로 분류되며, 국내에서 ..."
204,kia,더 프레스티지 K7,sedan,False,Kia K7 (Cadenza) is a full-size/mid-large seda...
205,kia,디 올 뉴 니로,suv,False,기아 니로는 소형 크로스오버 SUV로 공식 분류됨
206,kia,디 올 뉴 셀토스,suv,False,기아 셀토스는 제조사 기준 소형 SUV 모델
207,kia,디 올 뉴 스포티지,suv,False,Kia Sportage is a compact SUV; official model ...
208,kia,디 올 뉴 스포티지 하이브리드,suv,False,스포티지는 기아의 대표적인 컴팩트 SUV 모델이며 하이브리드 여부와 무관하게 차체 ...
209,kia,레이,hatchback,False,"기아 레이는 박스형 경차로 기본 차체는 해치백이며, 밴 트림도 동일 차체 기반"
210,kia,모닝 어반,hatchback,False,기아 모닝(피칸토) 기반의 경차 5도어 해치백 모델
211,kia,모하비,suv,False,기아 모하비는 프레임 바디 기반의 대형 SUV 모델
212,kia,모하비 더 마스터,suv,False,기아 모하비(더 마스터)는 바디온프레임 구조의 대형 SUV로 공식적으로 SUV로 분류됨
213,kia,봉고3,truck,False,Kia Bongo 3 is a light commercial pickup truck...
214,kia,셀토스,suv,False,기아 셀토스는 소형 SUV 모델
215,kia,스토닉,suv,False,기아 스토닉은 소형 크로스오버 SUV 모델
216,kia,스팅어,sedan,False,기아 스팅어는 4도어 패스트백(리프트백) 형태의 스포츠 세단으로 공식적으로 세단 라...
217,kia,스팅어 마이스터,sedan,False,Kia Stinger is a 4-door sports sedan (liftback...
218,kia,스포티지 4세대,suv,False,기아 스포티지는 전 세대에 걸쳐 준중형 SUV로 판매된 모델
219,kia,스포티지 더 볼드,suv,False,기아 스포티지는 대표적인 준중형 SUV 모델
220,kia,스포티지R,suv,False,기아 스포티지 R은 3세대 스포티지로 분류되는 준중형 SUV
221,kia,쏘렌토 4세대,suv,False,기아 쏘렌토는 4세대 포함 전 세대가 중형 SUV로 공식 분류됨
222,kia,쏘렌토 4세대 하이브리드,suv,False,기아 쏘렌토는 중형 SUV 모델이며 하이브리드 여부나 트림은 차체 유형을 바꾸지 않음
223,kia,쏘렌토R,suv,False,쏘렌토 R는 기아 쏘렌토 2세대 모델로 중형 SUV
224,kia,쏘울,suv,False,기아 공식 분류 및 시장 포지셔닝상 소형 SUV(박스형 크로스오버)
225,kia,쏘울 부스터,suv,False,기아 쏘울은 제조사 및 국내 시장에서 소형 SUV(박스형 크로스오버)로 분류됨
226,kia,오피러스 프리미엄,sedan,False,기아 오피러스(Amanti)는 대형 세단 모델
227,kia,올 뉴 K3,sedan,False,"K3는 기본적으로 4도어 준중형 세단이며, GT 5도어 해치백 트림이 존재하지만 모..."
228,kia,올 뉴 K7,sedan,False,Kia K7 (Cadenza) is a mid-to-large size passen...
229,kia,올 뉴 K7 하이브리드,sedan,False,Kia K7 (Cadenza) is a full-size/mid-large seda...
230,kia,올 뉴 모닝,hatchback,False,기아 모닝(피칸토)은 소형 5도어 해치백 모델
231,kia,올 뉴 모닝 [JA],hatchback,False,Kia Morning (Picanto) is a subcompact 5-door h...
232,kia,올 뉴 쏘렌토,suv,False,기아 쏘렌토는 중형 SUV 모델로 공식 분류됨
233,kia,올 뉴 쏘울,suv,False,Kia Soul is marketed and commonly classified a...
234,kia,올 뉴 카니발,van,False,카니발은 기아의 대표적인 대형 미니밴(MPV)으로 공식 모델 포지션이 승합/밴
235,kia,올 뉴 카렌스,van,False,카렌스는 5·7인승 MPV/미니밴 계열 모델
236,kia,올 뉴 프라이드,hatchback,False,국내에서 올 뉴 프라이드는 주로 소형 5도어 해치백 모델로 판매됨
237,kia,카니발 4세대,van,False,카니발은 기아의 대표적인 대형 미니밴(MPV) 모델
238,kia,타스만,truck,False,기아 타스만은 중형급 픽업 트럭으로 공식 발표된 모델
239,kia,텔루라이드,suv,False,기아 텔루라이드는 3열 중대형 SUV로 공식 모델 포지셔닝이 SUV임
240,kia,포르테,sedan,False,국내 판매된 기아 포르테는 기본 차체가 준중형 세단 모델
241,kia,포르테 쿱,coupe_convertible,False,포르테의 2도어 쿠페(Koup) 모델
242,kia,포르테 해치백,hatchback,False,포르테의 해치백 바디 타입 모델
243,renault,QM3,suv,False,Renault QM3 is a subcompact SUV/crossover (Cap...
244,renault,QM5,suv,False,Renault Samsung QM5 is a compact SUV (Korean-m...
245,renault,QM5 네오,suv,False,르노삼성 QM5 네오는 콜레오스 기반의 컴팩트 SUV 모델
246,renault,QM6,suv,False,Renault QM6 is a midsize SUV (Korean-market ve...
247,renault,SM3 네오,sedan,False,국내 르노삼성 SM3 네오는 4도어 컴팩트 세단 모델
248,renault,SM5 노바,sedan,False,Renault Samsung SM5 Nova is a D-segment midsiz...
249,renault,SM6,sedan,False,Renault Samsung SM6 is a mid-size four-door se...
250,renault,SM7 노바,sedan,False,르노삼성 SM7 노바는 국내 판매된 대형 세단 모델
251,renault,SM7 뉴 아트,sedan,False,르노삼성 SM7 뉴 아트는 국내 판매된 대형 세단 모델
252,renault,XM3,suv,False,Renault Korea XM3 is marketed as a coupe-style...
253,renault,그랑 콜레오스,suv,False,르노코리아 중형 SUV 모델
254,renault,뉴 QM3,suv,False,르노삼성 QM3는 르노 캡처 기반의 소형 SUV로 국내에서 소형 SUV로 판매
255,renault,뉴 QM5,suv,False,르노삼성 QM5는 콜레오스 기반의 컴팩트 SUV 모델
256,renault,뉴 SM3,sedan,False,Korean-market Renault Samsung SM3; compact/mid...
257,renault,뉴 SM5 (신형),sedan,False,르노삼성 SM5는 중형 세단으로 판매된 모델
258,renault,뉴 마스터,van,False,"르노 마스터는 대형 밴/미니버스 기반 상용·승합 차량으로 밴, 13·15인승, 캠핑..."
259,renault,뉴SM5 플래티넘,sedan,False,국내 판매된 르노삼성 SM5 플래티넘은 중형급 4도어 세단 모델
260,renault,더 뉴 QM6,suv,False,르노코리아 QM6는 중형 SUV 모델
261,renault,더 뉴 SM6,sedan,False,Renault Korea SM6 is a midsize 4-door sedan; t...
262,renault,마스터,van,False,"르노 마스터는 대형 상용 밴/미니버스 기반 모델로 13·15인승, 밴, 캠핑카 등 ..."
263,renault,올 뉴 SM7,sedan,False,None
264,renault,캡처,suv,False,르노 캡처는 B세그먼트 소형 SUV(크로스오버)로 공식 판매됨
265,renault,클리오,hatchback,False,르노 클리오는 전 세계적으로 판매된 소형 5도어 해치백 모델
266,renault,필랑트,sedan,True,"국내 자료 및 모델 설명에서 중대형 하이브리드 세단으로 소개됨 (차체 길이 약 4,..."

## Apply Mapping Table to Cohort Input

완성된 mapping table을 `cohort_grouping_input.csv`에 붙여서 category가 포함된 최종 파일을 만든다.

In [10]:
mapping_table_df = load_mapping_table(mapping_table_path)
cohort_grouping_with_category = apply_mapping_table(df, mapping_table_df)
output_path = DATA_PATH.parent / "cohort_grouping_with_category.csv"
cohort_grouping_with_category.to_csv(output_path, index=False)

print("mapped rows:", cohort_grouping_with_category[["major_category"]].dropna().shape[0])
display(cohort_grouping_with_category.head(30))
output_path

mapped rows: 5909

,brand,model_name,level_name,class_name,launch_price_krw,displacement_cc,body_length_mm,body_width_mm,body_height_mm,major_category
0,chevrolet,더 넥스트 스파크,1.0,LS,10360000,999,3595,1595,1475,hatchback
1,chevrolet,더 넥스트 스파크,1.0,LS 베이직,9990000,999,3595,1595,1475,hatchback
2,chevrolet,더 넥스트 스파크,1.0,LS 베이직,9990000,999,3595,1595,1475,hatchback
3,chevrolet,더 넥스트 스파크,1.0,LT,11340000,999,3595,1595,1475,hatchback
4,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,995,3595,1595,1475,hatchback
5,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,999,3595,1595,1475,hatchback
6,chevrolet,더 넥스트 스파크,1.0,LT 플러스,10360000,999,3595,1595,1475,hatchback
7,chevrolet,더 넥스트 스파크,1.0,LTZ,11360000,995,3595,1595,1475,hatchback
8,chevrolet,더 넥스트 스파크,1.0,LTZ,11340000,999,3595,1595,1475,hatchback
9,chevrolet,더 넥스트 스파크,1.0,LTZ,11340000,999,3595,1595,1475,hatchback
10,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,11360000,995,3595,1595,1475,hatchback
11,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,12060000,999,3595,1595,1475,hatchback
12,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 패션,12010000,999,3595,1595,1475,hatchback
13,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 퍼펙트 블랙,15090000,999,3595,1595,1475,hatchback
14,chevrolet,더 넥스트 스파크,1.0,스페셜 에디션 퍼펙트 블랙,15090000,999,3595,1595,1475,hatchback
15,chevrolet,더 넥스트 스파크,1.0,에코 LS,14320000,999,3595,1595,1475,hatchback
16,chevrolet,더 넥스트 스파크,1.0,에코 LS,14270000,999,3595,1595,1475,hatchback
17,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,12710000,999,3595,1595,1475,hatchback
18,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,14300000,999,3595,1595,1475,hatchback
19,chevrolet,더 넥스트 스파크,1.0,에코 LS 베이직,14300000,999,3595,1595,1475,hatchback
20,chevrolet,더 넥스트 스파크,1.0,에코 LT 플러스,12270000,995,3595,1595,1475,hatchback
21,chevrolet,더 넥스트 스파크,1.0,에코 LT 플러스,12270000,999,3595,1595,1475,hatchback
22,chevrolet,더 넥스트 스파크,1.0,에코 LT 플러스,12390000,999,3595,1595,1475,hatchback
23,chevrolet,더 넥스트 스파크,1.0,에코 LTZ,14990000,995,3595,1595,1475,hatchback
24,chevrolet,더 넥스트 스파크,1.0,에코 LTZ,15620000,999,3595,1595,1475,hatchback
25,chevrolet,더 넥스트 스파크,1.0,에코 LTZ,15590000,999,3595,1595,1475,hatchback
26,chevrolet,더 뉴 말리부,1.3 터보,LS,23450000,1341,4935,1855,1465,sedan
27,chevrolet,더 뉴 말리부,1.3 터보,LS 디럭스,24610000,1341,4935,1855,1465,sedan
28,chevrolet,더 뉴 말리부,1.3 터보,LT,25660000,1341,4935,1855,1465,sedan
29,chevrolet,더 뉴 말리부,1.3 터보,LT 디럭스,27410000,1341,4935,1855,1465,sedan

PosixPath('/Users/iwonbin/workspace/Study/boot/SKN28-1st-4team/data_collection/raw/models_cohort/cohort_generation/data/cohort_grouping_with_category.csv')